# Sample configuration for the options trader
# Duplicate entries are automatically removed.
tickers:
  - AAPL
  - MSFT
  - GOOGL
  - META

put_strike_pct: 0.9
call_strike_pct: 1.0
put_strike_variation: [-0.05, 0.0, 0.05]
min_days: 90
max_days: 270
expiry_step: 30
call_to_put_ratio: [1, 2]
risk_free_rate: 0.04
contract_size: 100
min_volatility: 0.15
max_volatility: 0.6
