# Example configuration for the options trader engine
# Values below reflect the synthetic long structure: buy 1 call, sell 2 puts.
tickers:
  - AAPL
  - MSFT
  - GOOGL
  - META
mode: automatic
risk_free_rate: 0.04
put_strike_pct: 0.9
call_strike_pct: 1.0
min_days: 90
max_days: 270
expiry_step: 30
call_to_put_ratio: [1, 2]
contract_size: 100
min_volatility: 0.1
max_volatility: 1.0
put_strike_variation: [-0.05, 0.0, 0.05]
